PROJECT_NAME: ""
PROJECT_VERSION: ""

LLM_URL: "http://<<please-set-llm-url>>"
LLM_API_TYPE: "nim"
LLM_MODEL_NAME: "llm-model"
EMBEDDINGS_LLM_URL: "http://<<please-set-embedding-llm-url>>"
EMBEDDINGS_LLM_MODEL_NAME: "embedding-llm-model"

INPUT_REPORT_FILE_PATH: "/path/to/report.html"
KNOWN_FALSE_POSITIVE_FILE_PATH: "/path/to/known_false_positives_file"
OUTPUT_FILE_PATH: "/path/to/output_excel.xlsx"
AGGREGATE_RESULTS_G_SHEET: ""
HUMAN_VERIFIED_FILE_PATH: ""
DOWNLOAD_REPO: false
REPO_REMOTE_URL: ""
REPO_LOCAL_PATH: "/path/to/repo"
LIBCLANG_PATH: "/path/to/libclang"
CONFIG_H_PATH: ""
COMPILE_COMMANDS_JSON_PATH: ""
SERVICE_ACCOUNT_JSON_PATH: ""

# Storage configuration
STORAGE_TYPE: "filesystem"  # Options: "filesystem", "s3"
# S3/MinIO configuration (used when STORAGE_TYPE is "s3")
S3_ENDPOINT: ""
S3_ACCESS_KEY: ""
S3_SECRET_KEY: ""
S3_BUCKET_DATASETS: "sast-datasets"
S3_BUCKET_TEMP: "sast-temp"
S3_REGION: "us-east-1"
S3_USE_SSL: false

USE_KNOWN_FALSE_POSITIVE_FILE: true
CALCULATE_RAGAS_METRICS: false
WRITE_RESULTS_INCLUDE_NON_FINAL: true

SHOW_FINAL_JUDGE_CONTEXT: true
SIMILARITY_ERROR_THRESHOLD: 2
MAX_ANALYSIS_ITERATIONS: 2

RUN_WITH_CRITIQUE: false
USE_CRITIQUE_AS_FINAL_RESULTS: false
CRITIQUE_LLM_URL: ""
CRITIQUE_LLM_MODEL_NAME: ""

CHUNK_SIZE: 500
CHUNK_OVERLAP: 0
CHUNK_SEPARATORS:
  - "\n\n"
  - "\n"
  - "."
  - ";"
  - ","
  - " "
  - ""
