apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-sast-ai-workflow
spec:
  params:
    - name: googleSpreadsheetUrl
      type: string
      description: "Google Spreadsheet URL"
    - name: LLM_URL
      type: string
      default: ""
    - name: LLM_MODEL_NAME
      type: string
      default: ""
    - name: EMBEDDINGS_LLM_URL
      type: string
      default: ""
    - name: EMBEDDINGS_LLM_MODEL_NAME
      type: string
      default: ""
    - name: PROJECT_NAME
      type: string
      default: ""
    - name: PROJECT_VERSION
      type: string
      default: ""
    - name: INPUT_REPORT_FILE_PATH
      type: string
      default: ""
  workspaces:
    - name: source-workspace
    - name: false-positives-workspace
    - name: llm-api-key-ws
    - name: embeddings-api-key-ws
    - name: google-sa-json-ws
  steps:
    - name: run-sast-ai-workflow
      image: quay.io/ecosystem-appeng/sast-ai-workflow:latest
      env:
        - name: LLM_URL
          value: "$(params.LLM_URL)"
        - name: LLM_MODEL_NAME
          value: "$(params.LLM_MODEL_NAME)"
        - name: EMBEDDINGS_LLM_URL
          value: "$(params.EMBEDDINGS_LLM_URL)"
        - name: EMBEDDINGS_LLM_MODEL_NAME
          value: "$(params.EMBEDDINGS_LLM_MODEL_NAME)"
        - name: PROJECT_NAME
          value: "$(params.PROJECT_NAME)"
        - name: PROJECT_VERSION
          value: "$(params.PROJECT_VERSION)"
        - name: INPUT_REPORT_FILE_PATH
          value: "$(params.INPUT_REPORT_FILE_PATH)"
        - name: LLM_API_KEY
          valueFrom:
            secretKeyRef:
              name: llm-api-key-secret
              key: api_key
        - name: EMBEDDINGS_API_KEY
          valueFrom:
            secretKeyRef:
              name: embeddings-api-key-secret
              key: api_key
        - name: GOOGLE_SERVICE_ACCOUNT_JSON_PATH
          value: "$(workspaces.google-sa-json-ws.path)/service_account.json"
      computeResources: 
        requests:
          ephemeral-storage: "2Gi"
        limits:
          ephemeral-storage: "4Gi"
      script: |
        #!/usr/bin/env sh
        echo "Running SAST-AI-Workflow..."
        python /app/src/run.py \
          --spreadsheet "$(params.googleSpreadsheetUrl)" \
          --source "$(workspaces.source-workspace.path)" \
          --false-positives "$(workspaces.false-positives-workspace.path)/ignore.err"

        
       