apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-sast-ai-workflow
spec:
  params:
    - name: googleSpreadsheetUrl
      type: string
      description: "Google Spreadsheet URL"
  workspaces:
    - name: source-workspace
    - name: false-positives-workspace
  steps:
    - name: run-sast-ai-workflow
      image: quay.io/ecosystem-appeng/sast-ai-workflow:latest
      env:
        - name: LLM_URL
          value: "$(params.LLM_URL)"
          default: ""
        - name: LLM_MODEL_NAME
          value: "$(params.LLM_MODEL_NAME)"
          default: ""
        - name: EMBEDDINGS_LLM_URL
          value: "$(params.EMBEDDINGS_LLM_URL)"
          default: ""
        - name: EMBEDDINGS_LLM_MODEL_NAME
          value: "$(params.EMBEDDINGS_LLM_MODEL_NAME)"
          default: ""
      script: |
        #!/usr/bin/env sh
        echo "Running SAST-AI-Workflow..."
        python /app/run.py \
          --spreadsheet "$(params.googleSpreadsheetUrl)" \
          --source "$(workspaces.source-workspace.path)" \
          --false-positives "$(workspaces.false-positives-workspace.path)/ignore.err"



