apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: validate-urls
spec:
  params:
    - name: sourceCodeUrl
      type: string
      description: "URL of the source code (RPM package or Git repository URL)"
    - name: spreadsheetUrl
      type: string
      description: "URL of the Google Spreadsheet"
    - name: falsePositivesUrl
      type: string
      description: "GitLab repository URL containing known false positive issues"
  steps:
    - name: validate-source-url
      image: curlimages/curl:latest
      script: |
        #!/usr/bin/env sh
        echo "Validating source code URL: $(params.sourceCodeUrl)"
        curl -ksSfL "$(params.sourceCodeUrl)" || (echo "Error: Source code URL is invalid" && exit 1)

    - name: validate-spreadsheet-url
      image: curlimages/curl:latest
      script: |
        #!/usr/bin/env sh
        echo "Validating spreadsheet URL: $(params.spreadsheetUrl)"
        curl -ksSfL "$(params.spreadsheetUrl)" || (echo "Error: Spreadsheet URL is invalid" && exit 1)

    - name: validate-false-positives-url
      image: curlimages/curl:latest
      script: |
        #!/usr/bin/env sh
        FP_URL="$(params.falsePositivesUrl)"
        echo "Validating false positives URL: $FP_URL"
        # If blank, skip. If not, ensure it's valid
        if [ -z "$FP_URL" ]; then
          echo "No false positives URL provided; skipping validation."
          exit 0
        fi
        curl -ksSfL "$FP_URL" || (echo "Error: False positives URL is invalid" && exit 1)
