apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sast-ai-workflow-pipeline
spec:
  params:
    - name: sourceCodeUrl
      type: string
      description: "Source code URL (RPM package or Git repository URL)"
    - name: falsePositivesUrl
      type: string
      description: "GitLab repository URL for known false positives (optional)"
    - name: LLM_URL
      type: string
      default: "http://<<please-set-llm-url>>"
    - name: LLM_MODEL_NAME
      type: string
      default: "llm-model"
    - name: EMBEDDINGS_LLM_URL
      type: string
      default: "http://<<please-set-embedding-llm-url>>"
    - name: EMBEDDINGS_LLM_MODEL_NAME
      type: string
      default: "embedding-llm-model"
    - name: PROJECT_NAME
      type: string
      default: "project-name"
    - name: PROJECT_VERSION
      type: string
      default: "project-version"
    - name: INPUT_REPORT_FILE_PATH
      type: string
      default: "input-report"
      
  workspaces:
    - name: shared-workspace
    - name: gitlab-token-ws
      optional: true
    - name: llm-api-key-ws 
    - name: embeddings-api-key-ws
    - name: google-sa-json-ws 
    - name: cache-workspace
  tasks:
    - name: validate-urls
      taskRef:
        name: validate-urls
      params:
        - name: sourceCodeUrl
          value: "$(params.sourceCodeUrl)"
        - name: INPUT_REPORT_FILE_PATH
          value: "$(params.INPUT_REPORT_FILE_PATH)"
        - name: falsePositivesUrl
          value: "$(params.falsePositivesUrl)"
      workspaces:
        - name: google-sa-json-ws
          workspace: google-sa-json-ws
    - name: prepare-source
      runAfter:
        - validate-urls
      taskRef:
        name: prepare-source
      params:
        - name: sourceCodeUrl
          value: "$(params.sourceCodeUrl)"
      workspaces:
        - name: source-workspace
          workspace: shared-workspace

    - name: fetch-false-positives
      runAfter:
        - validate-urls
      taskRef:
        name: fetch-false-positives
      params:
        - name: falsePositivesUrl
          value: "$(params.falsePositivesUrl)"
      workspaces:
        - name: false-positives-workspace
          workspace: shared-workspace
        - name: gitlab-token-ws
          workspace: gitlab-token-ws

    - name: run-sast-ai
      runAfter:
        - prepare-source
        - fetch-false-positives
      taskRef:
        name: execute-sast-ai-workflow
      params:
        - name: LLM_URL 
          value: "$(params.LLM_URL)"
        - name: LLM_MODEL_NAME
          value: "$(params.LLM_MODEL_NAME)"
        - name: EMBEDDINGS_LLM_URL 
          value: "$(params.EMBEDDINGS_LLM_URL)"
        - name: EMBEDDINGS_LLM_MODEL_NAME
          value: "$(params.EMBEDDINGS_LLM_MODEL_NAME)"
        - name: PROJECT_NAME 
          value: "$(params.PROJECT_NAME)"
        - name: PROJECT_VERSION
          value: "$(params.PROJECT_VERSION)"
        - name: INPUT_REPORT_FILE_PATH
          value: "$(params.INPUT_REPORT_FILE_PATH)"
          
      workspaces:
        - name: source-workspace
          workspace: shared-workspace
        - name: false-positives-workspace
          workspace: shared-workspace
        - name: llm-api-key-ws
          workspace: llm-api-key-ws
        - name: embeddings-api-key-ws 
          workspace: embeddings-api-key-ws
        - name: google-sa-json-ws
          workspace: google-sa-json-ws
        - name: cache-workspace
          workspace: cache-workspace
