name: "Code Review by Gemini AI"

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          # The clone URL of the forked repository
          PULL_REQUEST_HEAD_REPO_URL: "${{ github.event.pull_request.head.repo.clone_url }}"
          # The branch name of the pull request head (e.g., "feature-branch")
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
          # The branch name of the pull request base (e.g., "main")
          PULL_REQUEST_BASE_REF: "${{ github.event.pull_request.base.ref }}"
        run: |-
          # Add the forked repository, where the head branch exists, as a remote
          git remote add fork "${{ env.PULL_REQUEST_HEAD_REPO_URL }}"
          
          # Fetch the head branch from the fork and the base branch from origin
          git fetch fork "${{ env.PULL_REQUEST_HEAD_REF }}"
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}"

          # Checkout the head branch to work with it
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"

          # Create the diff against the base branch from the origin repository
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt"
          
          # Format the diff for the action output
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: "Code Review by Gemini AI"
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gemini-2.0-flash"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: |-
            Assume you are a senior python developer who has very good amount of common sense. Review the changes with the following key aspects in mind:
            - Check clarity on the content
            - Simple, straightforward code is almost always better
            - Has the developer created functions or classes to reduce duplication and complexity?
            - Is the code using an inefficient algorithm for a critical task? For example, using a list for lookups where a set or dictionary would be much faster (O(n) vs. O(1))
            - Exceptions should be as specific as possible, and the handling logic should be deliberate and safe
            Provide your comments in simple short concise manner.
          log_level: "DEBUG"
