name: Gemini AI Code Reviewer

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: sshnaidm/gemini-code-review-action@v1
        with:
          gemini-key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            Please review this code with focus on:
            - Design
            - Performance optimizations
            - Best practices
            - Readability
          add-files: 'true'
          context-lines: '20'
          review-title: 'Code Review by Gemini AI'
